version: "3.9"

services:
  discovery:
    build: ./eurekaServer-master
    ports:
      - "8761:8761"
    image: "discovery-service"

  user-service:
    build: ./user-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8080:8080"
    image: "user-service"
    depends_on:
      - gateway

  gateway:
    build: ./api_gateway
    ports:
      - "8089:8089"
    image: "gateway-service"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
